### ISSUE TITLE
Broken link in UVic wifi article

### ISSUE THREAD

**Issue by garetethan** [poanchen/poanchen.github.io#30]
I've found the article "[Connecting to UVic wifi with Ubuntu 16.04 LTS](https://poanchen.github.io/blog/2017/11/08/Connecting-to-UVic-wifi-with-Ubuntu-16.04-LTS)" to be useful in the past, but the link it gives to [UVic's certificate](https://www.uvic.ca/dl/public/fr.php?filename=GlobalSignRoot.cer) for Debian 9 is broken. <del>I am guessing that I should use this cert, as I am attempting to connect from Debian 10, and have been unsuccessful without it.</del>

<del>If the cert cannot be located, workaround suggestions would be appreciated.</del>

Update: I have managed to connect without the cert. But it would still be nice to have the broken link fixed if that's possible.

Thank you.

---
#### Document Details

⚠ *Do not edit this section.*

* Blog URL: [Connecting to UVic wifi with Ubuntu 16.04 LTS](https://poanchen.github.io/blog/2017/11/08/Connecting-to-UVic-wifi-with-Ubuntu-16.04-LTS)
* GitHub Source URL: [Connecting-to-UVic-wifi-with-Ubuntu-16.04-LTS.md](https://github.com/poanchen/poanchen.github.io/blob/will-jekyll-template/_posts/2017-11-08-Connecting-to-UVic-wifi-with-Ubuntu-16.04-LTS.md)

**Comment by poanchen** [comment]
Hey @garetethan thanks for the feedback. Feel free to fork this repo and create a PR to correct this post. So that student from Uvic can benefit from this. I no longer go to university anymore. Might be hard for me to keep track of these. Would be nice if you can contribute and update the post as you see fit. Thanks a bunch. Looking forward for your reply.

Thanks,
Baron

**Comment by poanchen** [comment]
Greatly appreciate your contribution @garetethan for the PR you did, https://github.com/poanchen/poanchen.github.io/pull/31

There were some deployment issues that I need to resolved. Now that it is fixed, and your changes is deployed to prod now. Thanks again for the help. Have a nice day!
