### ISSUE TITLE
Feedback on 'permission denied for relation' error.

### ISSUE THREAD

**Issue by jameshcovington** [poanchen/poanchen.github.io#43]
I realize this post is almost 5 years old, but I'm analyzing logs for Postgresql 15.1 and am seeing 'permission denied for table' vice 'permission denied for relation'. I suspect this is simply a logging format change with some version of Postgresql, but can you confirm?

---
#### Document Details

⚠ *Do not edit this section.*

* Blog URL: [How to fix permission denied for relation some_table_name in PostgreSQL?](https://poanchen.github.io/blog/2018/03/07/How-to-fix-permission-denied-for-relation-some_table_name-in-PostgreSQL)
* GitHub Source URL: [How-to-fix-permission-denied-for-relation-some_table_name-in-PostgreSQL.md](https://github.com/poanchen/poanchen.github.io/blob/will-jekyll-template/_posts/2018-03-07-How-to-fix-permission-denied-for-relation-some_table_name-in-PostgreSQL.md)

**Comment by poanchen** [comment]
@jameshcovington did you figure out this at the end?

**Comment by jameshcovington** [comment]
I think I concluded that the error "permission denied for table" is the same as the older "permission denied for relation", although I never got a definitive answer.

**Comment by poanchen** [comment]
Thanks will close this
